version: "3"
services:

  vjmysql:
    image: mysql/mysql-server:5.7
    container_name: vjmysql
    environment:
      MYSQL_ROOT_PASSWORD: "vjMysql@23456"
      MYSQL_ROOT_HOST: '%'
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - vjudge-network
    ports:
      - "3306:3306"

  vjtomcat:
    image: tomcat:8.0
    container_name: vjtomcat
    restart: always
    volumes:
      - ./data/tomcat/webapps:/usr/local/tomcat/webapps
      - ./data/tomcat/logs:/usr/local/tomcat/logs
    depends_on:
      - vjmysql
    networks:
      - vjudge-network
    ports:
      - "8080:8080"

networks:
  vjudge-network:
    driver: bridge
